-- Run as ACCOUNTADMIN (or TRANSFORM_ROLE, if it owns these schemas) AFTER
-- the load script and dbt have created RAW / staging / marts objects.
-- Uses FUTURE grants too, so REVIEWER_ROLE keeps read access as dbt
-- creates or replaces models on later runs, without re-granting by hand.

GRANT USAGE ON SCHEMA SALES_DB.RAW TO ROLE REVIEWER_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA SALES_DB.RAW TO ROLE REVIEWER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SALES_DB.RAW TO ROLE REVIEWER_ROLE;

GRANT USAGE ON SCHEMA SALES_DB.STAGING TO ROLE REVIEWER_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA SALES_DB.STAGING TO ROLE REVIEWER_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA SALES_DB.STAGING TO ROLE REVIEWER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SALES_DB.STAGING TO ROLE REVIEWER_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SALES_DB.STAGING TO ROLE REVIEWER_ROLE;

GRANT USAGE ON SCHEMA SALES_DB.MARTS TO ROLE REVIEWER_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA SALES_DB.MARTS TO ROLE REVIEWER_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA SALES_DB.MARTS TO ROLE REVIEWER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SALES_DB.MARTS TO ROLE REVIEWER_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SALES_DB.MARTS TO ROLE REVIEWER_ROLE;
